version: "3.8"

services:
  static-website:
    image: 390403859889.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
    container_name: static-website
    ports:
      - "80:80"
    restart: unless-stopped
